common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  username: root
  password: 20101992

development:
  <<: *common
  database: kaminari_demo_development

test:
  <<: *common
  database: kaminari_demo_test

staging:
  <<: *common
  database: kaminari_demo_staging

production:
  <<: *common
  database: kaminari_demo
