# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbf2962d53c6c6626a14df2087796dcd0f6552386b8a56243d803fd6e5c2205e2ec002563ec693d240b3a3c450a3bc8a0c3774b78a5c8c88504708f464e558f2

test:
  secret_key_base: 39cc4d38bd8212ee7ff4b048f65f3496dac0c5efd835adcc3fe22aa9620db13ccbd1e4d6d431af896cef238a0b6235c3d7dfee72512d17dc61a13b1429a2e4b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
